### ISSUE TITLE
finds no charts

### ISSUE THREAD

**Issue by macbuse** [chfw/echarts-scrappeteer#3]
Debian Buster
node 10.16.0

1/ https://pyecharts.github.io/ gives a response 404 in the browser 
so try https://github.com/pyecharts/pyecharts

2/ Found 0 echarts.

scrappeteer https://github.com/pyecharts/pyecharts

(node:28911) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/home/gregmcshane/.nvm/versions/node/v10.16.0/lib/node_modules/echarts-scrappeteer/node_modules/puppeteer/lib/NavigatorWatcher.js:69:21)
(node:28911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chfw** [comment]
well, on both websites, the charts are gif/jpeg.

so if you are after some testing link, you can use this one: https://echarts-maps.github.io/echarts-china-cities-js/shape-only-preview.html

**Comment by chfw** [comment]
or this website: http://gallery.pyecharts.org/#/Bar/bar_rotate_xaxis_label
